name: simple-kubernetes
runtime: yaml
resources:
  devNamespace:
    type: kubernetes:core:Namespace
    properties:
      metadata:
        name: "dev"
  nginxIngress:
    type: kubernetes:helm.sh:Chart
    properties:
      chart: "nginx-ingress"
      namespace: ${devNamespace.metadata.name}
      fetchOpts:
          repo: "https://charts.helm.sh/stable/"